export const SET_NUOVE_USCITE = "SET_NUOVE_USCITE";
export const SET_ALTRO_SCOPRIRE = "SET_ALTRO_SCOPRIRE";
export const SET_LOADING = "SET_LOADING";
export const SET_ERROR = "SET_ERROR";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const SET_CURRENT_SONG = "SET_CURRENT_SONG";
export const TOGGLE_PLAY = "TOGGLE_PLAY";
export const STOP_PLAY = "STOP_PLAY";
